### ISSUE TITLE
Since last update I can't add any domains nor certificates

### ISSUE THREAD

**Issue by mihail-minkov** [domainmod/domainmod#11]
I don't know what happened since the last update but I can't add any domains nor certiciates. I add them and it says domain/certificate added but when I go to the dashboard the numbers remain the same and when I go to the domain or certificate section the new one doesn't appear.

I also cannot disable the scheduled tasks, it says task disabled, but it keeps being active after refresh.

**Comment by chetcuti** [comment]
That's very strange, there was nothing in the last update that should be causing an issue like this, and nobody else has reported this problem.

Based on this ticket and the other one you submitted it seems like you're having some odd issues, and I'm wondering if they may be server-specific. If you're open to it, I would like to do some testing with your data. Please visit the following URL for more information, https://domainmod.org/gethelp/

**Comment by mihail-minkov** [comment]
Hello again, currently I have removed it from my server because it wasn't working although I really find it useful and I would like it to work. 

When I first installed it everything worked correctly. When I updated it, it stopped saving things in the database and that's when I reported the issue.

A few days ago I tried a clean install and it was showing me a bunch of errors (had to enable error_reporting and display_errors to see them) but the main issues I saw were incorrect default values for DATE fields in the database. I am not sure if this is what caused the issue, but I wasn't even able to do a clean install.

Also, as a recommendation, related to the other ticket would it be possible to configure SMTP credentials? That would be a huge plus.

**Comment by chetcuti** [comment]
The invalid datetime default value issue has been fixed (issue https://github.com/domainmod/domainmod/issues/9) and was included in last night's release (v4.01.007), so you should be able to install again.

As for entering specific SMTP credentials, unfortunately this isn't possible yet, but it's planned for the future.

**Comment by chetcuti** [comment]
I'm happy to announce that as of v4.02, DomainMOD now has SMTP support.

Regarding your issue with not being able to add domains or SSL certificates, I believe this has something to do with your server's settings, but without being able to test your live data in another environment to confirm it's hard to say for sure. I haven't been able to replicate this issue, and nobody else has reported it, which is why I believe it's server-specific. If an error_log file was generated please submit a new ticket with the exact error message you're receiving.

If you would like me to investigate this issue further please visit: https://domainmod.org/gethelp/
