### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by picarda** [domainmod/domainmod#113]
Hello,
I'm currently having this issue on a new installation.
Debian9 LAMP... With all the requirements install.

Any idea?

**Comment by paoloaq** [comment]
same here ... :(

**Comment by TheMadVanguard** [comment]
Out of interest what within the Apache error logs? It helped me overcome the 500 error.

**Comment by chetcuti** [comment]
Unfortunately Error 500 (Internal Server Error) is a very generic error that doesn't give much information as to what the actual problem is, so I would need more information from your web server logs in order to try to figure out what's going on.

Since these could all be separate issues that are just receiving the common Error 500, I'm going to close this issue, and if you're still experiencing this problem please open a new issue with some further information from your web server logs.
