### ISSUE TITLE
Changing password fails

### ISSUE THREAD

**Issue by Quin452** [domainmod/domainmod#119]
So I've logged in and changed the password, but then that password does not work.
No password works.

The only option is to reset the password, which then prompts me to change it again.

I've tried this many times.  As soon as I log out, I lose access.

**Comment by chetcuti** [comment]
I have a feeling you've either figured this out already or moved on to other software, but just in case...

What happens if you try to change the password to the one that was emailed to you when you reset your password? It should be a pretty basic password with no special characters that might cause problems, so if you "change" the password to it again, it should rule out the issue being caused by special characters in the password.

If that doesn't help, you may want to check your web server/PHP logs when the login fails to see if it's giving you any additional information about what's going wrong.
