### ISSUE TITLE
DomainMOD 4.18.0 force to redirect on https.

### ISSUE THREAD

**Issue by GaneshKandu** [domainmod/domainmod#138]
Hi,

I am tried to install DomainMOD  4.18.0 but i am faced loading issue.
all file except main page is loaded with secure http
but i haven't installed SSL Certificate.

**Comment by chetcuti** [comment]
The fact that you submitted this issue so soon after the new version was released told me that maybe I had made a mistake by implementing forced HTTPS. After some further thought, yes, I do believe I made a mistake doing this, and I have now reverted it so that although the option to force HTTPS is still there, it's disabled by default. If you install/upgrade to v4.18.01, you should be good-to-go now.

I recently signed up for a penetration testing service in order to do what I can to improve the security of the software even further, and I think I got a bit carried away implementing their recommendations. Now that I've given this more consideration I think it's better to have the option of forced HTTPS, but have it off by default, so that the majority of users don't end up with an annoying surprise when they install or upgrade, just like you did.

Thanks a lot for the report on this!

**Comment by GaneshKandu** [comment]
> v4.18.01, you should be good-to-go now.
Thanks !
