### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by m1guelpiedrafita** [domainmod/domainmod#14]
Could you please make a TODO.md file to let other users help in this project?
Thank you!

**Comment by chetcuti** [comment]
I've thought about adding this a bunch of times, but for various reasons it just doesn't seem like it would be worth the time at the moment. The primary reasons being...

- The software isn't nearly ready for more developers to come on board anyways (not only is there no developer or contributing documentation, there isn't even any end-user documentation yet)
- As I have a full-time job and working on DomainMOD is a part-time endeavour in my spare time, I would like to focus on the actual software when I have time instead of managing and remembering to update a TODO list
- I don't really want DomainMOD's competition to know what's being worked on :)

That said, this is still something I considr regularly, and at some point in the future it's probably going to happen, I'm just not sure if now is the right time.
