### ISSUE TITLE
PHP error: Column 'domain' cannot be null -- unable to import new domains

### ISSUE THREAD

**Issue by ctrlbrk42** [domainmod/domainmod#148]
Version 4.18.01

`
 PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'domain' cannot be null in /var/www/html/classes/DomainMOD/DomainQueue.php:874\nStack trace:\n#0 /var/www/html/classes/DomainMOD/DomainQueue.php(874): PDOStatement->execute()\n#1 /var/www/html/classes/DomainMOD/DomainQueue.php(171): DomainMOD\\DomainQueue->importToDomainQueue()\n#2 /var/www/html/admin/scheduler/run.php(180): DomainMOD\\DomainQueue->processQueueList()\n#3 {main}\n  thrown in /var/www/html/classes/DomainMOD/DomainQueue.php on line 874, referer: https://domainmod.xxxx.net/admin/scheduler/
`

**Comment by ctrlbrk42** [comment]
> You can see [here](https://github.com/domainmod/domainmod/blob/master/classes/DomainMOD/Csv.php) that the code expects you to organize the values exactly as it has been set on their [template](https://domainmod.org/import-template-sample.csv)

I'm importing via the api. Not csv or etc. The issue is a bug, and a show stopper for me.

**Comment by ctrlbrk42** [comment]
I guess this project is dead. Unfortunate.

**Comment by Qrzysio** [comment]
The last update was about a few weeks ago.

**Comment by ctrlbrk42** [comment]
Guess no one fixes obvious bugs on this project any longer. I was really excited once about it, but this show stopping bug put an end to that.

**Comment by gregdotca** [comment]
@ctrlbrk42 - I do apologize for not getting back to you on this, and I'm sorry that it soured you to DomainMOD, but I completely understand. I've been in the same boat myself, and was frustrated when I didn't get a response to an issue I submitted that was a deal breaker for me, so I literally know exactly how you feel. If you knew me you would know that I absolutely hate making people feel like this. Unfortunately the last few years have been a bit insane and I simply haven't had much time for DomainMOD. This is why I'm currently using the holidays from my day job to work on catching up on issues.

That said, if you do ever want to give the software another try, I would recommend trying out the Docker/Docker Compose installation method. With this installation method I'm able to fully control the setup of the operating system, which helps eliminate one-off issues as it means the environment that DomainMOD is running in is always the same. Though, there's currently an issue with the docker source code, but that will be fixed in the DomainMOD release that I'm going to be getting out at the end of this week (v4.22.0).
