### ISSUE TITLE
[Feature] Additional Notification Methods for Expiration Notifications

### ISSUE THREAD

**Issue by Alex-Ferdinand** [domainmod/domainmod#158]
Hello,
I have observed that there is currently only one method available for receiving expiration notifications. 
I believe it would be beneficial to have additional options, such as Telegram or Discord, available as well.

Thank you for your consideration.

Best regards.

**Comment by gregdotca** [comment]
This is absolutely something I want to get implemented. Someone submitted a similar request to our support portal not long after you posted here, and since this is a new feature request, I'm going to use that submission as the primary and close this ticket. I would recommend visiting the below URL and voting in order to get more eyes on the issue and help prioritize it.

https://support.domainmod.org/b/90pj1r0j/domainmod-support/additional-notification-options
