### ISSUE TITLE
Installation issue again

### ISSUE THREAD

**Issue by mihail-minkov** [domainmod/domainmod#16]
Hello, I know it's weird in my case, but I just tried installing the latest version and when I run install I get this error.

There was a problem retrieving the creation type ID

It won't advance from there and I haven't changed any server configuration since the last version that worked for me.

Did you make substantial schema changes? The issue in this case I think is database related rather than code related or permission related.

**Comment by mihail-minkov** [comment]
Hello, as a workaround, I tried installing it on a local Vagrant Ubuntu I have and it installed without any issues. So I installed it and then exported the database and imported it to the other one and it runs.

The problem is still there when I try to insert data. It works on the vagrant but doesn't work on the other server. I tried inserting an SSL provider and it supposedly got inserted and sent me to SSL provider accounts, but when I get there the provider does not appear.

What does work is the SMTP which is really nice 👍 

The only thing that occurs to me is that it might be either a PHP7 incompatibility which is not probable, or maybe some MySQL requirement. 

The differences between the two systems are:

> **Computer where I am having the installation issues**
> It runs on Ubuntu 16.04.1 LTS
> Operating System: Linux zebraserver 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64
> Web Server: Apache/2.4.20 (Ubuntu)
> PHP: 7.0.11-1+deb.sury.org~trusty+1
> MySQL: 5.7.16-0ubuntu0.16.04.1
> DomainMOD: 4.02.000 (4.02.000)

As you can see the computer is up-to-date, I am not sure what could be the cause of the issue there.

> **Vagrant Ubuntu where it installed without any issues**
> It runs on Ubuntu 14.04.5 LTS
> System Information
> Operating System: Linux vagrant-ubuntu-trusty-64 3.13.0-98-generic #145-Ubuntu SMP Sat Oct 8 20:13:07 UTC 2016 x86_64
> Web Server: Apache/2.4.7 (Ubuntu)
> PHP: 7.0.12-1+deb.sury.org~trusty+1
> MySQL: 5.5.53-0ubuntu0.14.04.1
> DomainMOD: 4.02.000 (4.02.000)

**Comment by chetcuti** [comment]
I think I know exactly what's going on here, and it was actually supposed to be fixed in an earlier release, but was somehow completely missed (I could swear I made the changes so I'm kind of baffled as to what happened). Basically, strict mode is probably enabled on your non-Vagrant MySQL, so when it tries to create the tables with default DATETIME values of "0000-00-00 00:00:00" it fails, since they aren't actually valid. And since it can't create the tables, everything else will fail.

I'm going to get this updated and pushed out to GitHub on my lunch break today.

As for why you can't insert data on the non-Vagrant system after importing the database tables, that's a bit of a mystery, unless it's the same issue and it can't insert the individual rows because the default is set to "0000-00-00 00:00:00". After you tried inserting an SSL provider was there an error_log file in the DomainMOD root folder or in the /ssl/ folder?

**Comment by mihail-minkov** [comment]
No, actually there's no error at all. I added error_reporting and nothing.

What I did manage to find was this:
```
Request URL: https://domain/domainmod/assets/add/ssl-provider.php
Request Method: POST
Status Code: **302 Found**
Remote Address: xxx.xxx.xxx.xxx:443
```

The 302 I think comes because of some redirects I do to force HTTPS, but I hadn't changed anything since the last version was working, so I don't think that should affect.

The form data is sent correctly
```
new_ssl_provider:StartSSL
new_url:https://www.startssl.com/
new_notes:
```

I don't know if an .htaccess with a RewriteBase should be added, but that would apply only to my case.

**Off-topic**: The codeigniter error I commented earlier on was caused because I have a CI installation in the parent folder so I think that was affecting the behavior. Perhaps that would merit an .htaccess in case someone else installs it in a folder whose parent has a framework like CodeIgniter or similar.

**Comment by mihail-minkov** [comment]
From what you're saying it might be probable because of the `0000-00-00 00:00:00` default value

**Comment by chetcuti** [comment]
No, I don't think the HTTPS redirect should affect anything. I do the same thing via .htaccess on every installation I use and it's never caused an issue.

Regarding CI and possibly including an .htaccess, I'll keep that in mind, however there are a lot of frameworks and platforms that I would need to take into consideration, so it would actually be a fairly big undertaking. Also, if DomainMOD is working properly and all redirects are functional, nobody should be getting 404 errors anyways, nor should they be accessing the parent folder, so if anything getting errors like you received with CI may just help with troubleshooting an issue that needs to be fixed.

I've updated the install script to not use 0000-00-00 00:00:00 for any of the default DATETIME values, and I'm guessing it may install for you now, so you may want to download the newest version and give it another try. And if I had to take a guess as to why data won't insert, it's because the update_time still has its default value set as 0000-00-00 00:00:00, so when a new row gets inserted and it tries to use that as the update_time value, it again has a problem because it's technically not a valid date/time. So I'm hoping this most  recent update will fix both the installation and insertion issues for you.

On a side note, I noticed you're trying to insert StartSSL as a provider. In case you haven't heard about the recent controversy surrounding them you may want to give a search for "startssl mozilla". The bottom line is, you should probably be trying to migrate away from using them for SSL certs. I loved everything about StartSSL and have used them for over 6 1/2 years, but recent events have made me start moving away from them as much as possible.

**Comment by mihail-minkov** [comment]
They say they're going to renew the CA certificate. Let's hope for the best.

**Comment by mihail-minkov** [comment]
Ok, everything is working fine now :)

I ran in 2 tiny details:

1. When I installed the fresh copy, once it had finished the install process fortunately without any issues, it told me it has to upgrade the database and when it did, several tables, like currencies and settings were empty and it was causing some issues, not sure if that should happen.

2. When there are inactive assets and I click to either show or hide them, I get this url

> https://domain/domainmod/settings/toggles/%2Fdomainmod%2Fassets%2Fregistrars.php 

and I get a 404 Error (regular this time, not the CodeIgniter one).

**Comment by chetcuti** [comment]
So after a fresh install the currencies and settings tables were completely empty, but after the database upgrade they weren't?

And it's very, very odd that it had to upgrade the database right after a fresh install, there's no reason for it to do that after a fresh installation as everything should already be up-to-date. Though if it couldn't insert the data into the settings table I guess  that does make a bit of sense, as it wouldn't have been able to retrieve the version number from the table and it would've seen it as a version mismatch (ie. needing to be upgraded).

So I guess the issue is that it didn't insert the initial settings information into the table. Hmm, let me look into this a bit, as this really doesn't make much sense.

**Comment by mihail-minkov** [comment]
Yes, it's really weird and I was recovering the stuff from my previous database, which at the moment had like 30 domains and a few certificates. The `0000-00-00 00:00:00` remains for some tables though.

I have inserted everything I had. When I go to Dashboard it shows me the numbers correctly.

When I get the expiration e-mail it sends the information correctly.

When I go to domains it returns empty and doesn't change no matter what.

In the Domain Registrar Accounts section it doesn't show the registrar accounts even if I have them in the database. Because of that I also can't add domains. Same goes for SSL certificates.

I think maybe rather than the update of domainmod, the issues started when I updated to Ubuntu 16.04 and MySQL 5.7. Why don't you put all the updated_time as NULL?

**Comment by mihail-minkov** [comment]
Actually several tables were empty so I would think the database wasn't correctly filled on install, which leads me again to the `0000-00-00 00:00:00` issue.

**Comment by chetcuti** [comment]
The issue you were having when trying to show or hide inactive assets has now been fixed and pushed to GitHub (dde3b572754a87df04ad9cfdbea7567bf79ad953), and the download file on domainmod.org has been updated as well.

I used to have the DATETIME fields as NULL a long time ago and that was causing some issues on its own, which is why I assigned default values. Now that they have a valid date for the default values though everything should be fine for new installs and upgrades, which is why I'm confused as to what's going on with your installation.

As for the other issues you're having, to be honest I'm not even sure what to suggest at this point, as they seem like completely random issues that shouldn't be happening, and they're fairly difficult to troubleshoot without being able to see the data or do some testing with it. If you're open to it, I would be willing to import your data into my test system so I can try to get to the bottom of this for you. If sharing your MySQL connection details makes you feel uncomfortable (which would be totally understandable), I have a Confidentiality Agreement you can fill out, which ensures your data will not be shared with anyone. For more information please visit https://domainmod.org/gethelp/

**Comment by mihail-minkov** [comment]
Hi again,

I would prefer to send you the mysql dump of the database of domainmod if that's all right with you. It's just that there's a lot of other stuff on the server.

I changed all the passwords to 1, so that should be no issue I think. You could try installing a fresh copy and run it with my database.

If that doesn't work I could zip the entire folder and send it to you.

You can download the zipped mysql dump from [here](https://www.zebravip.team/zdm_domainmod.zip)

**Comment by chetcuti** [comment]
In case you weren't already aware, these issue tickets are completely public, so unfortunately anyone was able to download your MySQL dump. I just downloaded it myself and removed the URL so that your data is private.

I'll do some testing on this when I have some time today and I'll let you know what I find.

**Comment by mihail-minkov** [comment]
Thanks for that :) let me know when you find out what's going on.

**Comment by chetcuti** [comment]
Alright, I think I've got this figured out, and the issues were all based around the `0000-00-00 00:00:00` problem and not being able to insert data in the database because of it.

To get your domains working, you need to delete the custom domain field "Uso interno". The custom field was created in the domain_fields table, but not in the domain_field_data table, and since those two tables couldn't be linked together some of the domain queries were breaking.

To get your SSL certs working all you need to do is update your currency conversion rates by going to _Maintenance_ -> _Update Conversion Rates_. You may also want to look into setting up the DomainMOD cron job so that your currency conversions get updated every night (along with running some other system tasks).

Give this a try and let me know how it goes.

**Comment by mihail-minkov** [comment]
Hello, deleting the "Uso interno" field did the trick but Update the conversion rates didn't work for the SSL Certificates. I do have the cronjob configured and it's executed regularly. What could that be about?

There's a small issue with the Task Scheduler. I am not sure if I should create a new issue about it, but I just can't disable tasks. It says it's been disabled but it remains active.

**Comment by mihail-minkov** [comment]
Also I noticed that after I deleted the "Uso interno" field I can see 20/25 of my domains, perhaps the ones with the "Uso interno" field checked. I am not sure.

I also can't see any of the Domain registrar accounts, but they do appear counted in the Domain registrars section.

**Comment by mihail-minkov** [comment]
Ok, tried adding a new domain, not working :(, not sure if it's because I manually rebuilt the database or some other issue.

**Comment by chetcuti** [comment]
Normally I would suggest a fresh install and re-entering your data instead of trying to import your previous data, however I'm not even sure if that will work for you, and I have a feeling your issues may be somehow related to your web server's configuration. I've done quite a bit of testing with your data and I just can't replicate your issues, they're all working fine for me in my test environment.

- Updating the conversion rates fixed the SSL certificates
- Disabling tasks is working for me
- I can see all 25 of your domains, not just 20 of them
- I can see the domain registrar accounts (6 accounts total)
- I can add new domains without issue

Given this, it doesn't seem as though the issues (at least not all of them) are related to you manually rebuilding your data, as I did the same thing and everything is working fine.

**Comment by mihail-minkov** [comment]
What are the specs of your test environment?

**Comment by mihail-minkov** [comment]
I ended up installing it on another server and it's working fine. Beats me why it's not working on the other server, my only theory remains MySQL 5.7 incompatibility, but anyway I am using it at the moment on the other server so everything is fine. You should just keep these changes in mind.
