### ISSUE TITLE
Import fails if a domain is expired

### ISSUE THREAD

**Issue by dcgavril** [domainmod/domainmod#24]
I've been struggling to import some domains through the Namesilo API, and it was always importing a part and failed right after it found a domain that expired (the domain is still in my list because it's not been dropped yet), but the queue doesn't continue when it gets to the expired domain. 

namesilo.class	error	Unable to get domain details

After the import, the domains were not showing in the list, even if the domain count was showing correctly on the main dashboard and after some debugging, I have seen that the pricing/fees were not inserted automatically (from the Namesilo API, or Dynadot...), and so I have started adding the fees and the domains have started to appear in the list. Maybe the list should show the domains even if there's no pricing (the pricing is changing quite often and if it's not automated there's no point in blocking the list view).

Anyway, thank you very much for your work!

**Comment by jennec** [comment]
I had the same issue with domains not showing. #29, if the fees were not added to the TLD.  I would prefer them to show regardless, otherwise you cannot manage your domains.  

My Fees were not updated via the API calls to GoDaddy either.  I assume they should be?

**Comment by chetcuti** [comment]
Stopping importing domains because it encounters an expired domain is definitely an issue that needs to be fixed. NameSilo doesn't have a test API, and I don't have any expired domains with them that I can use for live testing, but I'll investigate and see what can be done. Maybe their API has a flag to only retrieve active domains. Hopefully I'll be able to get something included in the next release that fixes this, and I'll keep you posted on this thread.

Regarding the domain fees, currently the fees do indeed need to be entered manually. Given how many registrars there are, how few of them actually give you the pricing information, and how many different fee structures there are even at the same registrar for different customers, updating the fees (and **keeping** them updated), is a fairly large undertaking. This is a feature that I would love myself, as I manage numerous installations of DomainMOD on a daily basis that span dozens of registrars, but it's just such a time-consuming addition to the software that it's unfortunately just not possible yet.

I want this feature so badly that I've even considered maintaining a database of the fees myself, and installations of DomainMOD would connect to my own server to update pricing instead of trying to rely on the domain registrars supplying pricing information via their API, but that's an even larger undertaking as I would need to setup my own API so people can connect and get the most up-to-date fees. I _will_ figure out how to solve this one day though, and in a way that doesn't make it an upkeep nightmare, which takes me away from focusing on the core functionality of DomainMOD.

**Comment by chetcuti** [comment]
I still haven't been able to replicate this issue, so I think maybe it was a temporary issue, or NameSilo's API possibly changed. I would recommend giving the newest version of DomainMOD a try (v4.11) and see if you still have the same problem.
