### ISSUE TITLE
Add web hosting accounts

### ISSUE THREAD

**Issue by dcgavril** [domainmod/domainmod#25]
I want to suggest if it's possible to add web hosting accounts the same way you have domain registrars or SSL accounts.
Thanks!

**Comment by chetcuti** [comment]
This is absolutely something that will come eventually, it's been on the todo list for a while now. When I originally started DomainMOD (before it even had a name) it was just something for myself and its only purpose was to manage domains, but my vision for the software has changed since then and things like Web Hosting, DNS, and IP Addresses should be managed similarly to domains so that the costs can all be tracked.

So I'm not sure how long it's going to be, but this will definitely be happening in a future version.
