### ISSUE TITLE
No way to state a different pricing per domain - for premium domains (gTLDs)

### ISSUE THREAD

**Issue by dcgavril** [domainmod/domainmod#26]
Hello,

I haven't found a way to change the pricing per domain, and that's needed when you have premium domains (gTLDs with special pricing from the general registry), so it's not a per extension pricing, it's per specific domain pricing. If there's already a way to deal with this, please advice.

Thanks.

**Comment by chetcuti** [comment]
Hmm... unfortunately there's no "clean" way to do this right now, but it's somewhat possible, sort of... ish. It would involve creating a new registrar and registrar account, moving the domain under this new account, and then setting the premium price for that registrar + TLD combo instead of the standard price. Definitely not ideal, but it would at least keep the financial tracking in DomainMOD accurate.

If you're not concerned with keeping the financial tracking accurate and you're mostly just wanting to keep track of how much you pay for the domain, you could also create a custom domain field, which would allow you to record the purchase/renewal/etc. price on a per-domain basis.

I'm going to try to figure out the best way to solve this long-term.

**Comment by chetcuti** [comment]
The two options mentioned above are going to be the best solutions for this for the time being, and I have this feature request recorded to figure out eventually, but for now I'm going to close this issue.

**Comment by jgod** [comment]
Is this still the best way?
