### ISSUE TITLE
Bug: Domain Queue - Fails on import for DNS-Domain and stops processing

### ISSUE THREAD

**Issue by jennec** [domainmod/domainmod#34]
Whilst using the Godaddy API, I tried to import all the 195 domains, but it stopped at 142.  I believe this might be because I have a number of domains that do not have GoDaddy as their Registrar, but GoDaddy has delegated control over their DNS records.  So these domains show in the list of Domains from GoDaddy and I think DomainMod doesn't get the expected result for these domains and stops. 

This might be similar to imports failing for expired domains as reported in issue #24.

**Comment by jennec** [comment]
Hi @chetcuti, any update on this issue?

**Comment by chetcuti** [comment]
I'm currently investigating the best way to get this resolved, but unfortunately GoDaddy's API doesn't seem to be able to import only domains that are registered with them, which make sense that it could cause some issues because DomainMOD will be expecting certain data to be returned but it won't be, since some of the domains may not actually be registered with them.

A way around this for now would be to use the Domain Queue to import your GoDaddy domains, but instead of allowing DomainMOD to retrieve the list of domains for you, copy and paste the list of domains in yourself. You won't have to supply any information other than the list of domains, and DomainMOD shouldn't have any issues retrieving the details because it will only attempt this for the domains that you've supplied (ie. domains that are actually registered with GoDaddy).

**Comment by chetcuti** [comment]
This issue was fixed in the newest version of DomainMOD ([v4.09.02](https://github.com/domainmod/domainmod/releases/tag/v4.09.02)).

I added some additional checks to the code so that it can now differentiate between domains that are registered with GoDaddy and domains that only have DNS hosting with GoDaddy, and domains that only have DNS hosting should no longer halt the importing.
