### ISSUE TITLE
GoDaddy API self signed cert

### ISSUE THREAD

**Issue by lucentminds** [domainmod/domainmod#36]
Getting "SSL certificate problem: self signed certificate in certificate chain" from php curl when using domainmod with goddady API. I fixed this by adding `curl_setopt($handle, CURLOPT_SSL_VERIFYPEER, 0);` in GoDaddy.php `function apiCall`.

**Comment by chetcuti** [comment]
Since all of the URLs that cURL connects to are hard-coded into the software, although I'm a bit apprehensive about disabling the verification, I don't really see an issue with it if it's going to help some people. I'm not sure why this would be failing for some people and not others though, I'm guessing it has something to do with the user's web server settings and not GoDaddy's API servers (otherwise it should be failing for everyone, but isn't).

This was implemented on all cURL requests in [v4.07.00](https://github.com/domainmod/domainmod/releases/tag/v4.07.00).
