### ISSUE TITLE
Segments: adding and editing

### ISSUE THREAD

**Issue by lucentminds** [domainmod/domainmod#42]
segments/add.php fails with error:   
**PHP Recoverable fatal error:  Object of class DomainMOD\Domain could not be converted to string in E:\data\wwwroot\lifecorp.com\domainmod\public_html\segments\add.php on line 139**

Once this is fixed, add.php does not initialize the `segment_data.update_time` field.
edit.php deletes the `segment_data.insert_time` field.
edit.php deletes all segment domains then reinserts them into `segment_data`.(_This is not an error, but seems like edit.php should update the `segment_data` record instead of delete it._)

**Comment by lucentminds** [comment]
Create a fix for the errors, but is the desired result of editing a segment to always delete then reinsert the same segment_data? Would it be better to query the existing domains, and update them?

**Comment by chetcuti** [comment]
Re: updating a segment always deleting and then re-inserting the data - I'll have to take another look at this. There were reasons why I did it this way, but I can't recall them off the top of my head. Since it's been a while since this was implemented now I'll take a look into this and see if maybe I can figure out a solution where the entries just get updated.

**Comment by chetcuti** [comment]
Segments have been updated so that they don't all get deleted and re-inserted when a segment is updated, and instead it will now just update existing entries and insert new ones. This is currently only in my local dev version but it will be included in the next release.

Thanks for pointing this out! I'm still not sure why I deleted and re-inserted everything with each update in the first place, probably because it was just easier and had the same result, with the exception of having more auto incrementing IDs taken up in the DB. But, now it feels like a better process, so I'm glad you reported this.
