### ISSUE TITLE
Getting PHP Notice when executing Cron Jobs

### ISSUE THREAD

**Issue by fingersonfire** [domainmod/domainmod#5]
Whenever I run the main cron job 

I get the following notice messages even if the variables are defined (all set to their default values)
PHP Notice:  Undefined variable: web_root in /path_to_domainmod/_includes/software.inc.php on line 26
PHP Notice:  Undefined index: HTTP_HOST in /path_to_domainmod/_includes/config-demo.inc.php on line 26
PHP Notice:  Undefined variable: demo_install in /path_to_domainmod/cron.php on line 43
PHP Notice:  Undefined index: s_message_success in /path_to_domainmod/classes/DomainMOD/Email.php on line 90

The cronjob is running properly according to Task Scheduler page.
The task is running under PHP 5.6 on a shared hosting provider

**Comment by chetcuti** [comment]
Things should still be running properly, these are just warnings because variables aren't specifically defined before they're used. These warnings are generally seen if the PHP error reporting is more on the strict side.

If you want to get rid of the warnings you can adjust your php.ini file to have less strict error reporting, or alternatively you can add "> /dev/null" (without the quotes) to the end of your PHP cron job call and errors will be suppressed.
