### ISSUE TITLE
install.php file has many syntax errors

### ISSUE THREAD

**Issue by domainsrock** [domainmod/domainmod#59]
latest version contains many syntax errors on install.php file.

**Comment by chetcuti** [comment]
Syntax errors that cause the installation to stop, or notices such as "undefined index" and "undefined variable"? We'll need more information in order to figure out what the issue might be.

**Comment by patrizi** [comment]
Hi, I've tried to install the app but it fail because of this: 

PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'ip' cannot be null in <install path>\classes\DomainMOD\Goal.php:55
Stack trace:
#0 <install path>\classes\DomainMOD\Goal.php(55): PDOStatement->execute()
#1 <install path>\install\go.php(1074): DomainMOD\Goal->installation()
#2 {main}
  thrown in <install path>\classes\DomainMOD\Goal.php on line 55

**Comment by chetcuti** [comment]
@patrizi, it sounds like you need to disable MySQL strict mode: https://domainmod.org/docs/userguide/troubleshooting/#strictmode

**Comment by patrizi** [comment]
Hi, 
no, the strict mode is not enable and (global) sql-mode variable have the value: "NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION".

N.B.: I'm using MariaDB

**Comment by chetcuti** [comment]
I would recommend giving v4.11 (which was released last night) a try, it has some changes that may fix this issue.

**Comment by chetcuti** [comment]
Closing old issue.
