### ISSUE TITLE
[EMERGENCY] A new version is NEEDED and IMPORTANT with all VULNERABILITY patches

### ISSUE THREAD

**Issue by Neustradamus** [domainmod/domainmod#90]
- https://www.cvedetails.com/vulnerability-list/vendor_id-18008/Domainmod.html

**Comment by chetcuti** [comment]
Closing this, as there are already issues open for them.

I'm working on these, but as someone who is not a developer by trade (ie. it takes some work to even figure out what the issues mean, nevermind fix them), has a full-time job and a family, and works on DomainMOD in my spare time, I can't always fix issues as soon as they happen. If you feel like submitting some pull requests to fix the issues though I'll happily review them.

Although the vulnerabilities are not ideal (and trust me, I really, really want them fixed as well), if you've followed the steps in the [Security section of the README](https://domainmod.org/readme/#security) your risk should be pretty limited, especially since DomainMOD is not a public website that's accessed by millions, and it generally only has one (or a few) trusted users.

Again though, I really want these fixed as well. I hate it that the software has any vulnerabilities at all, but there are only so many hours in a day.

**Comment by chetcuti** [comment]
FYI, these were all fixed in [v4.12.0](https://github.com/domainmod/domainmod/releases/tag/v4.12.0), which was released earlier today.
